channels:
- conda-forge
- patrikhlobil
dependencies:
- aiohttp
- black
- conda-merge
- fsspec
- geopandas
- invoke
- ipykernel
- ipython
- lxml
- mypy
- numpy
- openpyxl
- osmnx
- pandas
- pandas-bokeh
- pip
- ploomber
- ploomber >=0.12.8
- prefect
- pyarrow
- pygeos
- pygraphviz
- python
- python-dotenv
- requests
- s3fs
- seaborn
- pip:
  - codema-dev-tasks==0.1.0
  - prefect-geopandas-serializer
name: codema-dev-projects
