name: plot-cross-sector-demand-and-emissions
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ploomber >= 0.12.8
  - python-dotenv
  - pyarrow
  - s3fs
  - pyyaml
  - seaborn
  - openpyxl
  
  - pip
  - pip:
    - codema-dev-tasks==0.2.0