name: hdd
channels:
  - conda-forge
  - patrikhlobil 
dependencies:
  # DAG
  - prefect

  # load s3 credentials from .env
  - python-dotenv

  # notebooks
  - jupyter
  - papermill
  - jupytext

  # Data Wrangling
  - pandas
  - geopandas

  # Filesystem
  - fsspec
  - s3fs
  - openpyxl

  # Plotting
  - pandas-bokeh

  # Dev
  - mypy
  - black
  - isort
  - flake8