name: retrofit
channels:
  - conda-forge
dependencies:

  - fs-s3fs
  - ipykernel
  - papermill
  - nbconvert
  - jupytext

  # fugue dependencies
  - pandas
  - pyarrow
  - sqlalchemy
  
  # qpd dependencies
  - antlr4-python3-runtime
  - ciso8601
  - fs

  - pip
  - pip:
    - fugue
    - rcbm